version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expoferia_ing_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 100M
      MEMORY_LIMIT: 512M
      PMA_ABSOLUTE_URI: http://localhost:8080/
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_CONTROLHOST: db
      PMA_CONTROLPORT: 3306
      PMA_CONTROLUSER: root
      PMA_CONTROLPASS: rootpassword
      PMA_ALLOW_NO_PASSWORD: 'true'
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: